# Dependabotの設定ファイル - Dockerおよびpip依存関係の自動更新
version: 2
updates:
  # Docker (本番環境)
  - package-ecosystem: "docker"
    directory: "/docker/prod" # Dockerfileが置かれているディレクトリのパス (本番環境)
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Docker (開発環境)
  - package-ecosystem: "docker"
    directory: "/docker/dev" # Dockerfileが置かれているディレクトリのパス (開発環境)
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # pip (Python依存関係)
  - package-ecosystem: "pip"
    directory: "/src" # Pythonプロジェクトのディレクトリを指定
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
