- name: ":bug: バグ"
  color: "d73a4a"
  description: "バグ報告やバグ修正に関連するイシューやプルリクエストに適用します。"
- name: ":bulb: 改善or提案"
  color: "a2eeef"
  description: "プロジェクトの改善点や提案、一般的なフィードバックに使用します。"
- name: ":hammer: リファクタリング"
  color: "2CC86F"
  description: "コードの可読性や構造の改善、保守性の向上を目的とした変更に適用します。"
- name: ":lock: セキュリティ"
  color: "FBCA04"
  description: "セキュリティ関連の問題や改善提案に使用します。脆弱性の報告やセキュリティ機能の追加など。"
- name: ":memo: ドキュメンテーション"
  color: "0075ca"
  description: "ドキュメント関連の改善や更新、問題報告に使用します。"
- name: ":no_entry_sign: 取り消し・無効"
  color: "cfd3d7"
  description: "プロジェクトの範囲外、または不適切な内容のイシューやプルリクエストに使用します。"
- name: ":question: 質問"
  color: "FCF867"
  description: "追加の情報や明確化が必要なイシューやプルリクエストに使用します。"
- name: ":repeat: ヨコ展開・既存イシュー"
  color: "267C33"
  description: "既に報告されているイシューやプルリクエストと重複する内容に使用します。"
- name: ":rocket: パフォーマンス"
  color: "43B5C9"
  description: "システムやアプリケーションのパフォーマンス改善に関連するイシューやプルリクエストに使用します。"
- name: ":sparkles: 新機能"
  color: "6E1C51"
  description: "新しい機能の提案や要求に適用します。新規アイデアや機能拡張に関するイシューやプルリクエスト。"
- name: ":wastebasket: 残課題・作業不足"
  color: "ffffff"
  description: "現時点で対応する予定のないイシューやプルリクエストに適用します。"
