version: '3'

services:
  app:
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile  # 本番用のDockerfileへのパスを変更
    image: <TODO:application_name>:latest
    env_file:
      - ../../.env
    environment:
      - DEBUG_MODE=false
    volumes:
      - <TODO:log_dir>/<TODO:application_code>:/<TODO:application_code>/data/log

