version: '3'

services:
  php-apache:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: my-php-app:latest
    command: apache2-foreground
    ports:
      - "80:80"
    volumes:
      - ..:/app